const crypto=require('crypto');
function env(name){const v=process.env[name];if(!v)throw new Error(`Missing Netlify environment variable: ${name}`);return v}
function pin(){return process.env.SUMAQ_KITCHEN_STAFF_PIN||process.env.SUMAQ_RESERVATIONS_STAFF_PIN||''}
function clean(v,max=500){return String(v??'').trim().slice(0,max)}
function safeEqual(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function json(statusCode,body){return{statusCode,headers:{'Content-Type':'application/json','Cache-Control':'no-store'},body:JSON.stringify(body)}}
function sign(value){const p=pin();if(!p)throw new Error('Kitchen staff PIN is not configured.');return crypto.createHmac('sha256',p).update(value).digest('base64url')}
function createToken(name){const b=Buffer.from(JSON.stringify({name:clean(name,80)||'Kitchen',exp:Date.now()+12*60*60*1000})).toString('base64url');return `${b}.${sign(b)}`}
function verifyToken(event){const token=event.headers['x-sumaq-kitchen-token']||'';const [b,s]=String(token).split('.');if(!b||!s||!safeEqual(s,sign(b)))throw Object.assign(new Error('Kitchen session expired.'),{status:401});const p=JSON.parse(Buffer.from(b,'base64url').toString());if(Date.now()>Number(p.exp||0))throw Object.assign(new Error('Kitchen session expired.'),{status:401});return p}
async function request(path,{method='GET',body,prefer='return=representation'}={}){const base=env('SUPABASE_URL').replace(/\/$/,'');const key=env('SUPABASE_SERVICE_ROLE_KEY');const r=await fetch(`${base}/rest/v1/${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:prefer},body:body?JSON.stringify(body):undefined});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||`Supabase error ${r.status}`);return d}
async function list(){
  const orders=await request('orders?select=id,public_id,source_channel,external_order_id,customer_name,phone,pickup_date,pickup_time,fulfillment,notes,total,status,payment_status,kitchen_status,created_at&order=created_at.desc&limit=120');
  const ids=(orders||[]).map(o=>o.id);let items=[],jobs=[];
  if(ids.length){const inList=ids.join(',');items=await request(`order_items?order_id=in.(${inList})&select=id,order_id,product_name,quantity,line_total&order=id.asc`);jobs=await request(`kitchen_print_jobs?order_id=in.(${inList})&select=id,order_id,status,attempts,requested_at,printed_at,last_error&order=requested_at.desc`)}
  const byOrder={};for(const i of items||[])(byOrder[i.order_id]||(byOrder[i.order_id]=[])).push(i);const jobMap={};for(const j of jobs||[])if(!jobMap[j.order_id])jobMap[j.order_id]=j;
  return (orders||[]).map(o=>({...o,items:byOrder[o.id]||[],print_job:jobMap[o.id]||null}));
}
async function update(payload){const id=clean(payload.id,80);const allowed=new Set(['New','Preparing','Ready','Completed','Cancelled']);if(!allowed.has(payload.kitchenStatus))throw new Error('Invalid kitchen status.');const rows=await request(`orders?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{kitchen_status:payload.kitchenStatus,updated_at:new Date().toISOString()}});return rows?.[0]||null}
async function reprint(payload){const id=clean(payload.id,80);const existing=await request(`kitchen_print_jobs?order_id=eq.${encodeURIComponent(id)}&select=id`);if(existing?.length){return (await request(`kitchen_print_jobs?id=eq.${existing[0].id}`,{method:'PATCH',body:{status:'pending',requested_at:new Date().toISOString(),claimed_at:null,printed_at:null,last_error:'',updated_at:new Date().toISOString()}}))?.[0]||null}return (await request('kitchen_print_jobs',{method:'POST',body:{order_id:id,status:'pending',printer_target:'kitchen'}}))?.[0]||null}
exports.handler=async(event)=>{if(event.httpMethod!=='POST')return json(405,{error:'Method not allowed'});try{const{action,payload={}}=JSON.parse(event.body||'{}');if(action==='verify'){const expected=pin();if(!expected)throw new Error('Kitchen staff PIN is not configured.');const supplied=event.headers['x-sumaq-kitchen-pin']||'';if(!safeEqual(supplied,expected))throw Object.assign(new Error('Invalid kitchen PIN.'),{status:401});return json(200,{data:{token:createToken(event.headers['x-sumaq-kitchen-name']||'Kitchen')}})}verifyToken(event);if(action==='list')return json(200,{data:await list()});if(action==='update')return json(200,{data:await update(payload)});if(action==='reprint')return json(200,{data:await reprint(payload)});throw new Error('Unsupported action.')}catch(e){console.error(e);return json(e.status||400,{error:e.message||'Request failed'})}};
