(function(){
'use strict';
const PASSWORD_HASH='19f2270050ba72195a56b9dec7ea765c02497805a7dde78ac9fbc58a6c15a245';
const RES_KEY='sumaqReservations',EVENT_KEY='sumaqEventInquiries',ORDER_KEY='sumaqCommerceOrders',CATALOG_KEY='sumaqCatalogOverrides';
const $=id=>document.getElementById(id);
function read(key,fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function csvEscape(v){return `"${String(v??'').replaceAll('"','""')}"`}
function downloadCsv(name,rows){const url=URL.createObjectURL(new Blob([rows],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function fmtDate(s){return s?new Date(s).toLocaleString():''}
function money(n){return new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0))}
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function normalize(x){return Array.isArray(x)?{id:x[0],name:x[1],category:x[2],description:x[3],price:Number(x[4]),unit:x[5],image:x[6]}:{...x,price:Number(x.price)}}
const defaults={pickup:(window.SUMAQ_CATALOGS?.pickup||[]).map(normalize),shop:(window.SUMAQ_CATALOGS?.shop||[]).map(normalize)};
function catalogs(){const saved=read(CATALOG_KEY,{});return {pickup:Array.isArray(saved.pickup)?saved.pickup:defaults.pickup,shop:Array.isArray(saved.shop)?saved.shop:defaults.shop}}
function saveCatalogs(data){write(CATALOG_KEY,data);window.dispatchEvent(new Event('storage'))}
function openDashboard(){$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');renderAll()}
$('loginBtn').addEventListener('click',async()=>{if(await sha256($('pin').value)===PASSWORD_HASH){sessionStorage.setItem('sumaqAdminAuth','1');$('loginMsg').textContent='';openDashboard()}else $('loginMsg').textContent='Invalid password.'});
$('pin').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
$('logoutBtn').addEventListener('click',()=>{sessionStorage.removeItem('sumaqAdminAuth');location.reload()});
document.querySelectorAll('.admin-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.admin-tabs button').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.admin-panel').forEach(p=>p.classList.toggle('active',p.id===btn.dataset.tab))}));
function statusSelect(type,index,current,options){return `<select class="record-status" data-type="${type}" data-index="${index}">${options.map(o=>`<option${o===current?' selected':''}>${o}</option>`).join('')}</select>`}
function renderReservations(){const items=read(RES_KEY,[]);$('reservationsBody').innerHTML=items.length?items.map((r,i)=>`<tr><td>${esc(fmtDate(r.createdAt))}<br><small>${esc(r.id)}</small></td><td>${esc(r.date)}<br>${esc(r.time)}</td><td>${esc((r.firstName||'')+' '+(r.lastName||''))}</td><td>${esc(r.adults||0)} adults<br>${esc(r.minors||0)} minors<br>${esc(r.partySize||'')} total</td><td>${esc(r.phone)}<br>${esc(r.email)}</td><td>${money(r.depositAmount)}<br>${esc(r.paymentStatus)}</td><td>${statusSelect('reservation',i,r.status||'New',['New','Confirmed','Seated','Completed','Cancelled'])}</td><td>${esc(r.notes)}</td><td><button class="mini-btn delete-record" data-type="reservation" data-index="${i}">Delete</button></td></tr>`).join(''):'<tr><td colspan="9">No reservations saved in this browser yet.</td></tr>'}
function renderEvents(){const items=read(EVENT_KEY,[]);$('eventsBody').innerHTML=items.length?items.map((r,i)=>`<tr><td>${esc(fmtDate(r.createdAt))}<br><small>${esc(r.id)}</small></td><td>${esc((r.firstName||'')+' '+(r.lastName||''))}</td><td>${esc(r.email)}</td><td>${esc(r.phone)}</td><td>${esc(r.message)}</td><td>${statusSelect('event',i,r.status||'New',['New','Contacted','Quoted','Booked','Closed','Cancelled'])}</td><td><button class="mini-btn delete-record" data-type="event" data-index="${i}">Delete</button></td></tr>`).join(''):'<tr><td colspan="7">No private event inquiries saved in this browser yet.</td></tr>'}
document.addEventListener('change',e=>{if(!e.target.matches('.record-status'))return;const key=e.target.dataset.type==='reservation'?RES_KEY:EVENT_KEY,items=read(key,[]),i=Number(e.target.dataset.index);if(items[i]){items[i].status=e.target.value;write(key,items)}});
document.addEventListener('click',e=>{const b=e.target.closest('.delete-record');if(!b)return;const key=b.dataset.type==='reservation'?RES_KEY:EVENT_KEY,items=read(key,[]);if(confirm('Delete this record?')){items.splice(Number(b.dataset.index),1);write(key,items);renderReservations();renderEvents()}});
$('exportReservations').onclick=()=>{const items=read(RES_KEY,[]),header='ID,Created,Date,Time,First Name,Last Name,Phone,Email,Adults,Minors,Party Size,Deposit Amount,Payment Status,Status,Notes';downloadCsv('sumaq-reservations.csv',[header,...items.map(r=>[r.id,r.createdAt,r.date,r.time,r.firstName,r.lastName,r.phone,r.email,r.adults,r.minors,r.partySize,r.depositAmount,r.paymentStatus,r.status,r.notes].map(csvEscape).join(','))].join('\n'))};
$('exportEvents').onclick=()=>{const items=read(EVENT_KEY,[]),header='ID,Created,First Name,Last Name,Phone,Email,Message,Status';downloadCsv('sumaq-private-events.csv',[header,...items.map(r=>[r.id,r.createdAt,r.firstName,r.lastName,r.phone,r.email,r.message,r.status].map(csvEscape).join(','))].join('\n'))};
$('clearReservations').onclick=()=>{if(confirm('Clear all reservations saved in this browser?')){localStorage.removeItem(RES_KEY);renderReservations()}};
$('clearEvents').onclick=()=>{if(confirm('Clear all event inquiries saved in this browser?')){localStorage.removeItem(EVENT_KEY);renderEvents()}};
function renderCatalog(type){const root=$(type==='pickup'?'pickupEditor':'shopEditor'),items=catalogs()[type];root.innerHTML=items.map((item,i)=>`<article class="admin-product-card"><img src="${esc(item.image)}" alt=""><div><span class="eyebrow">${esc(item.category)}</span><h3>${esc(item.name)}</h3><p>${esc(item.description)}</p><strong>${money(item.price)} · ${esc(item.unit)}</strong><div class="admin-card-actions"><button class="mini-btn edit-product" data-type="${type}" data-index="${i}">Edit</button><button class="mini-btn danger delete-product" data-type="${type}" data-index="${i}">Delete</button></div></div></article>`).join('')||'<p>No items yet.</p>'}
const modal=$('productModal'),form=$('productForm');
function openProduct(type,index){const data=catalogs(),item=Number.isInteger(index)?data[type][index]:{id:'',name:'',category:'',description:'',price:'',unit:'',image:'assets/photos/02-menu-img-2709.webp'};$('productModalTitle').textContent=Number.isInteger(index)?'Edit item':'Add new item';$('productType').value=type;$('productOriginalId').value=Number.isInteger(index)?item.id:'';$('productId').value=item.id;$('productName').value=item.name;$('productCategory').value=item.category;$('productPrice').value=item.price;$('productUnit').value=item.unit;$('productDescription').value=item.description;$('productImage').value=item.image;$('productPreview').src=item.image;modal.classList.remove('hidden')}
function closeProduct(){modal.classList.add('hidden');form.reset();$('productImageFile').value=''}
document.querySelectorAll('.add-product').forEach(b=>b.onclick=()=>openProduct(b.dataset.type));
document.addEventListener('click',e=>{const edit=e.target.closest('.edit-product'),del=e.target.closest('.delete-product');if(edit)openProduct(edit.dataset.type,Number(edit.dataset.index));if(del&&confirm('Delete this catalogue item?')){const data=catalogs();data[del.dataset.type].splice(Number(del.dataset.index),1);saveCatalogs(data);renderCatalog(del.dataset.type)}});
$('closeProductModal').onclick=$('cancelProduct').onclick=closeProduct;
$('productImage').addEventListener('input',()=>{$('productPreview').src=$('productImage').value||''});
$('productImageFile').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const img=new Image(),reader=new FileReader();reader.onload=()=>{img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const url=canvas.toDataURL('image/webp',.78);$('productImage').value=url;$('productPreview').src=url};img.src=reader.result};reader.readAsDataURL(file)});
form.addEventListener('submit',e=>{e.preventDefault();const type=$('productType').value,data=catalogs(),original=$('productOriginalId').value,item={id:$('productId').value.trim(),name:$('productName').value.trim(),category:$('productCategory').value.trim(),description:$('productDescription').value.trim(),price:Number($('productPrice').value),unit:$('productUnit').value.trim(),image:$('productImage').value.trim()};if(data[type].some(x=>x.id===item.id&&x.id!==original)){alert('That item ID already exists.');return}const index=data[type].findIndex(x=>x.id===original);if(index>=0)data[type][index]=item;else data[type].push(item);try{saveCatalogs(data)}catch(err){alert('The browser could not save this image. Try a smaller image or use an image URL.');return}renderCatalog(type);closeProduct()});
let currentCommerceRows=[];function dateValue(id,end){const v=$(id).value;if(!v)return null;const d=new Date(v+'T00:00:00');if(end)d.setHours(23,59,59,999);return d}
function runCommerceReport(){const type=$('reportType').value,from=dateValue('reportFrom'),to=dateValue('reportTo',true),orders=read(ORDER_KEY,[]).filter(o=>o.type===type&&(!from||new Date(o.createdAt)>=from)&&(!to||new Date(o.createdAt)<=to));const gross=orders.reduce((s,o)=>s+Number(o.total||0),0),tax=orders.reduce((s,o)=>s+Number(o.tax||0),0);$('metricOrders').textContent=orders.length;$('metricGross').textContent=money(gross);$('metricTax').textContent=money(tax);$('metricAverage').textContent=money(orders.length?gross/orders.length:0);const map={};orders.forEach(o=>(o.items||[]).forEach(i=>{const k=i.name||i.id;if(!map[k])map[k]={name:k,qty:0,sales:0};map[k].qty+=Number(i.qty||0);map[k].sales+=Number(i.qty||0)*Number(i.price||0)}));currentCommerceRows=Object.values(map).sort((a,b)=>b.sales-a.sales);$('productSalesBody').innerHTML=currentCommerceRows.length?currentCommerceRows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.qty}</td><td>${money(r.sales)}</td></tr>`).join(''):'<tr><td colspan="3">No sales for this selection.</td></tr>'}
$('runReport').onclick=runCommerceReport;$('exportCommerce').onclick=()=>downloadCsv(`sumaq-${$('reportType').value}-sales.csv`,['Item,Units Sold,Sales CAD',...currentCommerceRows.map(r=>[r.name,r.qty,r.sales.toFixed(2)].map(csvEscape).join(','))].join('\n'));
function renderAll(){renderReservations();renderEvents();renderCatalog('pickup');renderCatalog('shop');runCommerceReport()}
if(sessionStorage.getItem('sumaqAdminAuth')==='1')openDashboard();
}());
