const PASSWORD_HASH='ae208b74a32e4148f03aa5b03a89252d2dd0c87a222ce794eab749606249b5f9';
const RES_KEY='sumaqReservations',EVENT_KEY='sumaqEventInquiries',ORDER_KEY='sumaqCommerceOrders';
const $=id=>document.getElementById(id);
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function csvEscape(v){return `"${String(v??'').replaceAll('"','""')}"`}
function downloadCsv(name,rows){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function fmtDate(s){return s?new Date(s).toLocaleString():''}
function money(n){return new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0))}
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function openDashboard(){$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');renderReservations();renderEvents();runCommerceReport()}
$('loginBtn')?.addEventListener('click',async()=>{if(await sha256($('pin').value)===PASSWORD_HASH){sessionStorage.setItem('sumaqAdminAuth','1');openDashboard()}else $('loginMsg').textContent='Invalid password.'});
$('pin')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
function renderReservations(){const items=read(RES_KEY,[]);$('reservationsBody').innerHTML=items.length?items.map(r=>`<tr><td>${fmtDate(r.createdAt)}<br><small>${r.id||''}</small></td><td>${r.date||''}<br>${r.time||''}</td><td>${r.firstName||''} ${r.lastName||''}</td><td>${r.adults||0} adults<br>${r.minors||0} minors<br>${r.partySize||''} total</td><td>${r.phone||''}<br>${r.email||''}</td><td>${money(r.depositAmount)}<br>${r.paymentStatus||''}</td><td><span class="pill">${r.status||'New'}</span></td><td>${r.notes||''}</td></tr>`).join(''):'<tr><td colspan="8">No reservations saved in this browser yet.</td></tr>'}
function renderEvents(){const items=read(EVENT_KEY,[]);$('eventsBody').innerHTML=items.length?items.map(r=>`<tr><td>${fmtDate(r.createdAt)}<br><small>${r.id||''}</small></td><td>${r.firstName||''} ${r.lastName||''}</td><td>${r.email||''}</td><td>${r.phone||''}</td><td>${r.message||''}</td><td><span class="pill">${r.status||'New'}</span></td></tr>`).join(''):'<tr><td colspan="6">No private event inquiries saved in this browser yet.</td></tr>'}
$('exportReservations')?.addEventListener('click',()=>{const items=read(RES_KEY,[]),header='ID,Created,Date,Time,First Name,Last Name,Phone,Email,Adults,Minors,Party Size,Deposit Required,Deposit Amount,Payment Status,Status,Notes';const rows=items.map(r=>[r.id,r.createdAt,r.date,r.time,r.firstName,r.lastName,r.phone,r.email,r.adults,r.minors,r.partySize,r.depositRequired,r.depositAmount,r.paymentStatus,r.status,r.notes].map(csvEscape).join(','));downloadCsv('sumaq-reservations.csv',[header,...rows].join('\n'))});
$('exportEvents')?.addEventListener('click',()=>{const items=read(EVENT_KEY,[]),header='ID,Created,First Name,Last Name,Phone,Email,Message,Status';const rows=items.map(r=>[r.id,r.createdAt,r.firstName,r.lastName,r.phone,r.email,r.message,r.status].map(csvEscape).join(','));downloadCsv('sumaq-private-events.csv',[header,...rows].join('\n'))});
$('clearReservations')?.addEventListener('click',()=>{if(confirm('Clear all reservation records saved in this browser?')){localStorage.removeItem(RES_KEY);renderReservations()}});
$('clearEvents')?.addEventListener('click',()=>{if(confirm('Clear all private event inquiries saved in this browser?')){localStorage.removeItem(EVENT_KEY);renderEvents()}});
let currentCommerceRows=[];
function dateValue(id,end=false){const v=$(id)?.value;if(!v)return null;const d=new Date(v+'T00:00:00');if(end)d.setHours(23,59,59,999);return d}
function runCommerceReport(){const type=$('reportType')?.value||'pickup',from=dateValue('reportFrom'),to=dateValue('reportTo',true);const orders=read(ORDER_KEY,[]).filter(o=>o.type===type&&(!from||new Date(o.createdAt)>=from)&&(!to||new Date(o.createdAt)<=to));const gross=orders.reduce((s,o)=>s+Number(o.total||0),0),tax=orders.reduce((s,o)=>s+Number(o.tax||0),0);$('metricOrders').textContent=orders.length;$('metricGross').textContent=money(gross);$('metricTax').textContent=money(tax);$('metricAverage').textContent=money(orders.length?gross/orders.length:0);const map={};orders.forEach(o=>(o.items||[]).forEach(i=>{const k=i.name||i.id;if(!map[k])map[k]={name:k,qty:0,sales:0};map[k].qty+=Number(i.qty||0);map[k].sales+=Number(i.qty||0)*Number(i.price||0)}));currentCommerceRows=Object.values(map).sort((a,b)=>b.sales-a.sales);$('productSalesBody').innerHTML=currentCommerceRows.length?currentCommerceRows.map(r=>`<tr><td>${r.name}</td><td>${r.qty}</td><td>${money(r.sales)}</td></tr>`).join(''):'<tr><td colspan="3">No sales for this selection.</td></tr>'}
$('runReport')?.addEventListener('click',runCommerceReport);
$('exportCommerce')?.addEventListener('click',()=>{const rows=['Item,Units Sold,Sales CAD',...currentCommerceRows.map(r=>[r.name,r.qty,r.sales.toFixed(2)].map(csvEscape).join(','))];downloadCsv(`sumaq-${$('reportType').value}-sales.csv`,rows.join('\n'))});
if(sessionStorage.getItem('sumaqAdminAuth')==='1')openDashboard();
