const PIN='SUMAQ2026';const CONFIG_KEY='sumaqReservationConfig';const RES_KEY='sumaqReservations';const EVENT_KEY='sumaqEventInquiries';const DEFAULT_CONFIG={depositRequired:false,adultDeposit:0,minorDeposit:0,currency:'CAD'};
const $=id=>document.getElementById(id);function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}function write(key,value){localStorage.setItem(key,JSON.stringify(value))}function csvEscape(v){return `"${String(v??'').replaceAll('"','""')}"`}function downloadCsv(name,rows){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows],{type:'text/csv'}));a.download=name;a.click()}function fmtDate(s){return s?new Date(s).toLocaleString():''}function money(n){return `$${Number(n||0).toFixed(2)} CAD`}
$('loginBtn').onclick=()=>{if($('pin').value.trim()===PIN){$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');loadAll()}else{$('loginMsg').textContent='Invalid PIN.'}};
function loadAll(){const c={...DEFAULT_CONFIG,...read(CONFIG_KEY,DEFAULT_CONFIG)};$('depositRequired').value=String(!!c.depositRequired);$('adultDeposit').value=c.adultDeposit||0;$('minorDeposit').value=c.minorDeposit||0;renderReservations();renderEvents()}
$('saveConfig').onclick=()=>{write(CONFIG_KEY,{depositRequired:$('depositRequired').value==='true',adultDeposit:Number($('adultDeposit').value||0),minorDeposit:Number($('minorDeposit').value||0),currency:'CAD'});$('configMsg').textContent='Configuration saved in this browser.'};
function renderReservations(){const items=read(RES_KEY,[]);$('reservationsBody').innerHTML=items.length?items.map(r=>`<tr><td>${fmtDate(r.createdAt)}<br><small>${r.id||''}</small></td><td>${r.date||''}<br>${r.time||''}</td><td>${r.firstName||''} ${r.lastName||''}</td><td>${r.adults||0} adults<br>${r.minors||0} minors<br>${r.partySize||''} total</td><td>${r.phone||''}<br>${r.email||''}</td><td>${money(r.depositAmount)}<br>${r.paymentStatus||''}</td><td><span class="pill">${r.status||'New'}</span></td><td>${r.notes||''}</td></tr>`).join(''):'<tr><td colspan="8">No reservations saved in this browser yet.</td></tr>'}
function renderEvents(){const items=read(EVENT_KEY,[]);$('eventsBody').innerHTML=items.length?items.map(r=>`<tr><td>${fmtDate(r.createdAt)}<br><small>${r.id||''}</small></td><td>${r.firstName||''} ${r.lastName||''}</td><td>${r.email||''}</td><td>${r.phone||''}</td><td>${r.message||''}</td><td><span class="pill">${r.status||'New'}</span></td></tr>`).join(''):'<tr><td colspan="6">No private event inquiries saved in this browser yet.</td></tr>'}
$('exportReservations').onclick=()=>{const items=read(RES_KEY,[]);const header='ID,Created,Date,Time,First Name,Last Name,Phone,Email,Adults,Minors,Party Size,Deposit Required,Deposit Amount,Payment Status,Status,Notes';const rows=items.map(r=>[r.id,r.createdAt,r.date,r.time,r.firstName,r.lastName,r.phone,r.email,r.adults,r.minors,r.partySize,r.depositRequired,r.depositAmount,r.paymentStatus,r.status,r.notes].map(csvEscape).join(','));downloadCsv('sumaq-reservations.csv',[header,...rows].join('\n'))};
$('exportEvents').onclick=()=>{const items=read(EVENT_KEY,[]);const header='ID,Created,First Name,Last Name,Phone,Email,Message,Status';const rows=items.map(r=>[r.id,r.createdAt,r.firstName,r.lastName,r.phone,r.email,r.message,r.status].map(csvEscape).join(','));downloadCsv('sumaq-private-events.csv',[header,...rows].join('\n'))};
$('clearReservations').onclick=()=>{if(confirm('Clear all reservation records saved in this browser?')){localStorage.removeItem(RES_KEY);renderReservations()}};$('clearEvents').onclick=()=>{if(confirm('Clear all private event inquiries saved in this browser?')){localStorage.removeItem(EVENT_KEY);renderEvents()}};
