(function(){
'use strict';
const mode=document.body.dataset.commerce||'';
const cartKey='sumaqCart_'+mode;
const pendingKey='sumaqPendingCommerceOrder';
let items=[];
let cart=read(cartKey,[]);
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function money(v){return new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(v)||0)}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function find(id){return items.find(x=>x.id===id)}
function subtotal(){return cart.reduce((s,l)=>{const i=find(l.id);return s+(i?Number(i.price)*Number(l.qty||0):0)},0)}
function setStatus(text,error=false){const el=document.getElementById('checkoutMsg');if(el){el.textContent=text;el.classList.toggle('error',error)}}
function renderMenu(){const root=document.getElementById('catalog');if(!root)return;if(!items.length){root.innerHTML='<div class="catalog-error"><h3>Menu temporarily unavailable</h3><p>The central catalogue could not be loaded.</p></div>';return}const cats=[...new Set(items.map(i=>i.category))];const q=new URLSearchParams(location.search).get('category');if(q&&cats.includes(q))root.dataset.category=q;const selected=root.dataset.category||'All';const visible=selected==='All'?items:items.filter(i=>i.category===selected);root.innerHTML='<div class="category-filter" style="grid-column:1/-1">'+['All',...cats].map(c=>`<button type="button" class="${selected===c?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')+'</div>'+visible.map(i=>`<article class="product-card"><img src="${esc(i.image)}" alt="${esc(i.name)}" loading="lazy"><div class="product-copy"><span class="eyebrow">${esc(i.category)}</span><h3>${esc(i.name)}</h3><p>${esc(i.description)}</p><div class="product-meta"><strong>${money(i.price)}</strong><small>per ${esc(i.unit)}</small></div><div class="product-order-controls"><label>Quantity<input class="catalog-qty" type="number" min="1" max="99" value="1"></label><button class="btn primary add-to-order" type="button" data-id="${esc(i.id)}">Add to order</button></div></div></article>`).join('');root.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{root.dataset.category=b.dataset.category;renderMenu()});root.querySelectorAll('.add-to-order').forEach(b=>b.onclick=()=>{const qty=Math.max(1,Math.min(99,Number(b.closest('.product-copy').querySelector('.catalog-qty').value)||1));const line=cart.find(l=>l.id===b.dataset.id);if(line)line.qty+=qty;else cart.push({id:b.dataset.id,qty});write(cartKey,cart);renderCart();b.textContent='Added ✓';setTimeout(()=>b.textContent='Add to order',900)})}
function renderCart(){const root=document.getElementById('cartItems');const count=cart.reduce((s,l)=>s+Number(l.qty||0),0);document.querySelectorAll('[data-cart-count]').forEach(n=>n.textContent=count);if(!root)return;root.innerHTML=cart.length?cart.map(l=>{const i=find(l.id);return i?`<div class="cart-row"><img src="${esc(i.image)}" alt=""><div><strong>${esc(i.name)}</strong><small>${money(i.price)} / ${esc(i.unit)}</small></div><div class="qty"><button type="button" data-action="minus" data-id="${esc(l.id)}">−</button><span>${l.qty}</span><button type="button" data-action="plus" data-id="${esc(l.id)}">+</button></div><strong>${money(Number(i.price)*Number(l.qty))}</strong></div>`:''}).join(''):'<p class="empty-state">Your cart is empty. Select a quantity and add your favourites.</p>';const sub=subtotal(),tax=sub*.05;document.getElementById('subtotal').textContent=money(sub);document.getElementById('tax').textContent=money(tax);document.getElementById('grandTotal').textContent=money(sub+tax);root.querySelectorAll('button[data-action]').forEach(b=>b.onclick=()=>{const l=cart.find(x=>x.id===b.dataset.id);if(!l)return;l.qty+=b.dataset.action==='plus'?1:-1;cart=cart.filter(x=>x.qty>0);write(cartKey,cart);renderCart()})}
async function init(){try{if(!window.SumaQData?.configured)throw new Error('Central catalogue is not configured.');items=await SumaQData.catalog(mode);renderMenu();renderCart();const params=new URLSearchParams(location.search);if(params.get('payment')==='success'){setStatus(`Demo payment approved. Order ${params.get('order')||''} is confirmed and shared with SumaQ.`);history.replaceState({},'',location.pathname)}}catch(err){console.error(err);renderMenu();setStatus(err.message,true)}}
const form=document.getElementById('checkoutForm');form?.addEventListener('submit',async e=>{e.preventDefault();if(!cart.length){alert('Please add at least one item to your order.');return}if(!form.reportValidity())return;if(!window.SumaQData?.configured){setStatus('Central ordering is not configured yet.',true);return}const button=form.querySelector('button[type="submit"]');button.disabled=true;try{const customer=Object.fromEntries(new FormData(form).entries()),sub=Number(subtotal().toFixed(2)),tax=Number((sub*.05).toFixed(2));const order={id:'SQ-'+Date.now().toString(36).toUpperCase(),type:mode,createdAt:new Date().toISOString(),status:'Awaiting payment',paymentStatus:'Pending (demo)',items:cart.map(l=>{const i=find(l.id);return {...i,qty:l.qty}}),subtotal:sub,tax,total:Number((sub+tax).toFixed(2)),...customer};await SumaQData.callFunction('create-order',order);sessionStorage.setItem(pendingKey,JSON.stringify(order));sessionStorage.setItem('sumaqPendingOrder',JSON.stringify({mode}));location.href='order-payment.html'}catch(err){setStatus(err.message,true);button.disabled=false}});
init();
}());
