const MODE=document.body.dataset.commerce; const KEY=`sumaqCart_${MODE}`; const ORDER_KEY='sumaqCommerceOrders';
const catalog=window.SUMAQ_CATALOGS?.[MODE]||[];
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n||0);
let cart=read(KEY,[]);
function product(id){return catalog.find(p=>p.id===id)}
function total(){return cart.reduce((s,i)=>s+(product(i.id)?.price||0)*i.qty,0)}
function renderCatalog(){const root=document.getElementById('catalog'); if(!root)return; root.innerHTML=catalog.map(p=>`<article class="product-card"><img src="${p.image}" alt="${p.name}" loading="lazy"><div class="product-copy"><span class="eyebrow">${p.category}</span><h3>${p.name}</h3><p>${p.description}</p><div class="product-meta"><strong>${money(p.price)}</strong><small>per ${p.unit}</small></div><button class="btn primary add" data-id="${p.id}">Add to cart</button></div></article>`).join(''); root.querySelectorAll('.add').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.id);x?x.qty++:cart.push({id:b.dataset.id,qty:1});write(KEY,cart);renderCart();});}
function renderCart(){const root=document.getElementById('cartItems'); const count=document.querySelectorAll('[data-cart-count]'); count.forEach(x=>x.textContent=cart.reduce((s,i)=>s+i.qty,0)); if(!root)return; root.innerHTML=cart.length?cart.map(i=>{const p=product(i.id);return `<div class="cart-row"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><small>${money(p.price)} / ${p.unit}</small></div><div class="qty"><button data-act="minus" data-id="${i.id}">−</button><span>${i.qty}</span><button data-act="plus" data-id="${i.id}">+</button></div><strong>${money(p.price*i.qty)}</strong></div>`}).join(''):'<p class="empty-state">Your cart is empty.</p>'; document.getElementById('subtotal').textContent=money(total());document.getElementById('tax').textContent=money(total()*.05);document.getElementById('grandTotal').textContent=money(total()*1.05);root.querySelectorAll('button').forEach(b=>b.onclick=()=>{const i=cart.find(x=>x.id===b.dataset.id);if(b.dataset.act==='plus')i.qty++;else i.qty--;cart=cart.filter(x=>x.qty>0);write(KEY,cart);renderCart()});}
const form=document.getElementById('checkoutForm');form?.addEventListener('submit',async e=>{e.preventDefault();if(!cart.length)return alert('Please add at least one item.');const fd=Object.fromEntries(new FormData(form).entries());const order={id:'SQ-'+Date.now().toString(36).toUpperCase(),type:MODE,createdAt:new Date().toISOString(),status:'New',paymentStatus:'Pending',items:cart.map(i=>({...i,...product(i.id)})),subtotal:total(),tax:total()*.05,total:total()*1.05,...fd};const orders=read(ORDER_KEY,[]);orders.unshift(order);write(ORDER_KEY,orders);try{const r=await fetch('/.netlify/functions/sumaq-create-order-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order})});const d=await r.json();if(d.url){location.href=d.url;return}}catch{} cart=[];write(KEY,cart);renderCart();document.getElementById('checkoutMsg').textContent=`Order ${order.id} saved. Stripe must be configured in Netlify to collect payment.`;form.reset();});
renderCatalog();renderCart();
