const DEFAULT_CONFIG={depositRequired:true,adultDeposit:50,minorDeposit:0,currency:'CAD',depositThreshold:4};
const toggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav-links');
toggle?.addEventListener('click',()=>nav.classList.toggle('open'));
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
function totalParty(){const a=Number(document.getElementById('adults')?.value||0);const m=Number(document.getElementById('minors')?.value||0);return {adults:a,minors:m,total:a+m}}
function calculateDeposit(){return totalParty().total>DEFAULT_CONFIG.depositThreshold?50:0}
function updatePartyAndPayment(){const p=totalParty();const partySize=document.getElementById('partySize');if(partySize)partySize.value=`${p.total} guest${p.total===1?'':'s'}`;const amount=calculateDeposit();const payBox=document.getElementById('paymentBox');const noPay=document.getElementById('noPaymentBox');const summary=document.getElementById('paymentSummary');if(payBox&&noPay){payBox.hidden=amount<=0;noPay.hidden=amount>0;if(amount>0&&summary)summary.textContent='When you select Book Now, you will continue to the secure payment preview.'}}
['adults','minors'].forEach(id=>document.getElementById(id)?.addEventListener('input',updatePartyAndPayment));updatePartyAndPayment();
function setBusy(form,busy){const b=form?.querySelector('button[type="submit"]');if(b)b.disabled=busy}
function showMessage(id,text,error=false){const el=document.getElementById(id);if(el){el.textContent=text;el.classList.toggle('error',error)}}
const reservationForm=document.getElementById('reservationForm');
reservationForm?.addEventListener('submit',async e=>{e.preventDefault();if(!window.SumaQData?.configured){showMessage('reservationMsg','Online reservations are being configured. Please call SumaQ to reserve.',true);return}const fd=Object.fromEntries(new FormData(reservationForm).entries()),p=totalParty(),deposit=calculateDeposit();const reservation={...fd,status:deposit>0?'Awaiting deposit':'Booked',paymentStatus:deposit>0?'Pending':'No payment required',depositRequired:deposit>0,depositAmount:deposit,adults:p.adults,minors:p.minors,partySize:p.total};if(deposit>0){sessionStorage.setItem('sumaqPendingReservation',JSON.stringify(reservation));showMessage('reservationMsg','A CAD 50 deposit is required. Opening the payment preview…');setBusy(reservationForm,true);location.href='reservation-payment.html';return}try{setBusy(reservationForm,true);await SumaQData.callFunction('create-reservation',reservation);showMessage('reservationMsg','Reservation booked successfully. SumaQ can now see it from every authorized device.');reservationForm.reset();document.getElementById('adults').value='2';document.getElementById('minors').value='0';updatePartyAndPayment()}catch(err){showMessage('reservationMsg',err.message,true)}finally{setBusy(reservationForm,false)}});
const eventForm=document.getElementById('eventForm');
eventForm?.addEventListener('submit',async e=>{e.preventDefault();if(!window.SumaQData?.configured){showMessage('eventMsg','Online event inquiries are being configured. Please contact SumaQ directly.',true);return}try{setBusy(eventForm,true);const inquiry=Object.fromEntries(new FormData(eventForm).entries());await SumaQData.callFunction('create-event',inquiry);showMessage('eventMsg','Private event inquiry sent successfully. SumaQ can now review it from any authorized device.');eventForm.reset()}catch(err){showMessage('eventMsg',err.message,true)}finally{setBusy(eventForm,false)}});
