'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const cfg=window.LUBOUTIQUE_CONFIG||{};
let products=[];
let cart=JSON.parse(localStorage.getItem('luCart')||'[]');
const money=n=>n>0?new Intl.NumberFormat(cfg.locale||'en-CA',{style:'currency',currency:cfg.currency||'CAD',maximumFractionDigits:0}).format(n):'Por confirmar';
const escapeHTML=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
function saveCart(){localStorage.setItem('luCart',JSON.stringify(cart));renderCart();}
function cartQty(){return cart.reduce((n,x)=>n+(x.qty||1),0)}
function subtotal(){return cart.reduce((n,x)=>n+(Number(x.price)||0)*(x.qty||1),0)}
function renderProducts(filter='Todos'){
 const grid=$('#productGrid'); if(!grid)return;
 const list=products.filter(p=>filter==='Todos'||p.category===filter);
 grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><img loading="lazy" src="${escapeHTML(p.image)}" alt="${escapeHTML(p.name)}"><span class="badge">${escapeHTML(p.badge||p.brand)}</span></div><div class="product-body"><div class="product-meta">${escapeHTML(p.brand)} · ${escapeHTML(p.category)}</div><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.description)}</p><strong class="price">${p.price>0?money(p.price):escapeHTML(p.priceLabel||'Consultar')}</strong><div class="option-row"><label>Talla<select id="size-${escapeHTML(p.id)}">${p.sizes.map(v=>`<option>${escapeHTML(v)}</option>`).join('')}</select></label><label>Color<select id="color-${escapeHTML(p.id)}">${p.colors.map(v=>`<option>${escapeHTML(v)}</option>`).join('')}</select></label></div><button class="btn primary full" data-add="${escapeHTML(p.id)}">Agregar a mi selección</button></div></article>`).join('')||'<p>No hay productos en esta categoría.</p>';
}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const size=$(`#size-${CSS.escape(id)}`)?.value||'',color=$(`#color-${CSS.escape(id)}`)?.value||'';const found=cart.find(x=>x.id===id&&x.size===size&&x.color===color);found?found.qty++:cart.push({...p,size,color,qty:1});saveCart();openCart();}
function changeQty(i,d){cart[i].qty=Math.max(1,(cart[i].qty||1)+d);saveCart()}
function removeItem(i){cart.splice(i,1);saveCart()}
function renderCart(){const list=$('#cartItems');if(!list)return;$('#cartCount').textContent=cartQty();$('#barItems').textContent=`${cartQty()} ${cartQty()===1?'artículo seleccionado':'artículos seleccionados'}`;$('#cartTotal').textContent=subtotal()>0?money(subtotal()):'Por confirmar';list.innerHTML=cart.length?cart.map((x,i)=>`<article class="cart-item"><img src="${escapeHTML(x.image)}" alt=""><div><strong>${escapeHTML(x.name)}</strong><small>${escapeHTML(x.size)} · ${escapeHTML(x.color)}</small><div class="qty"><button data-qty="${i},-1" aria-label="Reducir">−</button><span>${x.qty||1}</span><button data-qty="${i},1" aria-label="Aumentar">+</button></div></div><button class="remove" data-remove="${i}" aria-label="Eliminar">×</button></article>`).join(''):'<p class="empty">Tu selección está vacía.</p>'}
function openCart(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show');$('#cartDrawer').setAttribute('aria-hidden','false')}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show');$('#cartDrawer').setAttribute('aria-hidden','true')}
function orderText(){const lines=cart.map((x,i)=>`${i+1}. ${x.name} | Talla: ${x.size} | Color: ${x.color} | Cantidad: ${x.qty||1}`).join('\n');return `Hola ${cfg.storeName||'LuBoutique'}, deseo confirmar disponibilidad de esta selección:\n\n${lines||'Necesito asesoría de compra.'}\n\nTotal estimado: ${subtotal()>0?money(subtotal()):'por confirmar'}\n\nNombre:\nCiudad:`}
function sendWhatsApp(){if(!cfg.whatsapp){alert('Configure el número de WhatsApp en data/config.js para activar esta función.');return}window.open(`https://wa.me/${cfg.whatsapp}?text=${encodeURIComponent(orderText())}`,'_blank','noopener')}
function sendEmail(){if(!cfg.email){alert('Configure el correo en data/config.js para activar esta función.');return}location.href=`mailto:${cfg.email}?subject=${encodeURIComponent('Solicitud LuBoutique')}&body=${encodeURIComponent(orderText())}`}
fetch('data/products.json').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{products=d;renderProducts();renderCart()}).catch(()=>{$('#productGrid').innerHTML='<p>No fue posible cargar el catálogo.</p>'});
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)addToCart(add.dataset.add);const rem=e.target.closest('[data-remove]');if(rem)removeItem(Number(rem.dataset.remove));const q=e.target.closest('[data-qty]');if(q){const [i,d]=q.dataset.qty.split(',').map(Number);changeQty(i,d)}});
$('.menu-toggle')?.addEventListener('click',e=>{const open=$('.nav-links').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>$('.nav-links').classList.remove('open')));
$('#openCart')?.addEventListener('click',openCart);$('#openCart2')?.addEventListener('click',openCart);$('#closeCart')?.addEventListener('click',closeCart);$('#overlay')?.addEventListener('click',closeCart);$('#clearCart')?.addEventListener('click',()=>{cart=[];saveCart()});$('#whatsappOrder')?.addEventListener('click',sendWhatsApp);$('#emailOrder')?.addEventListener('click',sendEmail);$('#contactWhatsapp')?.addEventListener('click',sendWhatsApp);$('#contactEmail')?.addEventListener('click',e=>{e.preventDefault();sendEmail()});
$('#filters')?.addEventListener('click',e=>{if(!e.target.matches('button'))return;$$('#filters button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');renderProducts(e.target.dataset.filter)});$$('[data-jump-filter]').forEach(a=>a.addEventListener('click',()=>{const f=a.dataset.jumpFilter;setTimeout(()=>{$(`#filters button[data-filter="${f}"]`)?.click()},100)}));
$('#vipForm')?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());data.createdAt=new Date().toISOString();const arr=JSON.parse(localStorage.getItem('luVipClients')||'[]');arr.push(data);localStorage.setItem('luVipClients',JSON.stringify(arr));$('#vipOk').textContent='Registro guardado correctamente.';e.target.reset()});
$('#year').textContent=new Date().getFullYear();$('#footerLocation').textContent=cfg.city||cfg.address||'';$$('[data-social]').forEach(a=>{const u=cfg[a.dataset.social];if(u){a.href=u;a.target='_blank';a.rel='noopener noreferrer';a.hidden=false}});if(cfg.email||cfg.whatsapp)$('#contactFallback').hidden=true;
