(function(){
const form=document.getElementById('bookingForm');if(!form)return;
const list=document.getElementById('bookingServiceList'),summary=document.getElementById('bookingSummary'),dateEl=document.getElementById('bookingDate'),slots=document.getElementById('timeSlots'),timeInput=document.getElementById('bookingTime'),msg=document.getElementById('bookingMsg');
const selected=new Map();let services=[];let timer=null;
function setMsg(t,c=''){msg.textContent=t||'';msg.className='note'+(c?' '+c:'')}
function renderServices(){list.innerHTML=services.filter(s=>s.active!==false).map(s=>`<div class="booking-service-option"><label class="service-choice"><input type="checkbox" data-service="${s.id}"><span><strong>${RBM.escapeHtml(s.name)}</strong><small>${RBM.escapeHtml(s.description)}</small><b>Prix confirmé sur soumission</b></span></label><label class="service-hours">Durée estimée<input type="number" data-hours="${s.id}" min="${s.minimum||1}" step="0.5" value="${s.minimum||1}" disabled></label></div>`).join('');list.querySelectorAll('[data-service]').forEach(c=>c.onchange=()=>{const s=services.find(x=>x.id===c.dataset.service),h=list.querySelector(`[data-hours="${s.id}"]`);h.disabled=!c.checked;if(c.checked)selected.set(s.id,{service_id:s.id,name:s.name,price:Number(s.price||0),unit:s.unit,qty:Number(h.value)});else selected.delete(s.id);sync()});list.querySelectorAll('[data-hours]').forEach(h=>h.oninput=()=>{if(selected.has(h.dataset.hours)){const x=selected.get(h.dataset.hours);x.qty=Math.max(Number(h.value)||1,Number(h.min)||1);selected.set(h.dataset.hours,x);sync()}})}
function sync(){const items=[...selected.values()];summary.innerHTML=items.length?items.map(i=>`<div class="cart-line"><div><strong>${RBM.escapeHtml(i.name)}</strong><br><small>Durée estimée : ${i.qty} h</small></div><strong>Sur devis</strong></div>`).join('')+'<div class="notice">Le prix sera confirmé avant le service.</div>':'<p class="muted-light">Aucun service sélectionné.</p>'}
const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());dateEl.min=now.toISOString().split('T')[0];
async function availability(d){if(!RBMData.configured())return ['8:00 AM','10:00 AM','12:00 PM','2:00 PM','4:00 PM','6:00 PM','8:00 PM'].map(slot=>({slot_label:slot,state:'available'}));return RBMData.rpc('get_public_day_availability',{p_date:d})}
async function renderSlots(preserve=false){if(!dateEl.value){slots.innerHTML='<span class="note">Choisissez une date pour voir les créneaux.</span>';return}const old=preserve?timeInput.value:'';slots.innerHTML='<span class="note">Vérification des disponibilités…</span>';try{const rows=await availability(dateEl.value);slots.innerHTML=rows.map(r=>{const st=String(r.state||'available').toLowerCase(),lab=st==='available'?'Disponible':st==='booked'?'Réservé':'Indisponible';return `<button type="button" class="time-slot ${st}${old===r.slot_label&&st==='available'?' selected':''}" data-time="${RBM.escapeHtml(r.slot_label)}" ${st!=='available'?'disabled':''}>${RBM.escapeHtml(r.slot_label)}<small>${lab}</small></button>`}).join('');slots.querySelectorAll('.time-slot.available').forEach(b=>b.onclick=()=>{slots.querySelectorAll('.time-slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');timeInput.value=b.dataset.time})}catch(e){slots.innerHTML='<div class="notice">Le calendrier en ligne est temporairement indisponible. Appelez le 438-866-2383.</div>'}}
dateEl.onchange=()=>renderSlots(false);
form.onsubmit=async e=>{e.preventDefault();const items=[...selected.values()];if(!items.length)return setMsg('Sélectionnez au moins un service.','error');if(!dateEl.value||!timeInput.value)return setMsg('Choisissez une date et un créneau disponible.','error');if(!RBMData.configured())return setMsg('La nouvelle base de données Groupe VGC doit être configurée avant les réservations en ligne. Vous pouvez nous appeler au 438-866-2383.','error');const d=Object.fromEntries(new FormData(form).entries()),btn=form.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Envoi de la demande…';try{const result=await RBMData.rpc('create_public_booking',{p_first_name:d.firstName,p_last_name:d.lastName,p_phone:d.phone,p_email:d.email,p_service_date:d.date,p_start_slot:timeInput.value,p_origin:d.origin,p_destination:d.destination||'',p_details:d.details||'',p_items:items.map(i=>({service_id:i.service_id,qty:i.qty}))});const row=Array.isArray(result)?result[0]:result;const b={reference:row.booking_reference,firstName:d.firstName,lastName:d.lastName,date:d.date,time:timeInput.value,items};sessionStorage.setItem('vgc_last_booking',JSON.stringify(b));location.href='booking-confirmation.html'}catch(err){console.error(err);setMsg('Impossible de confirmer la demande. Veuillez réessayer ou appeler le 438-866-2383.','error');btn.disabled=false;btn.textContent='Envoyer ma demande'}};
(async()=>{services=await RBM.getServices();renderServices();sync();renderSlots();timer=setInterval(()=>dateEl.value&&renderSlots(true),30000)})();window.addEventListener('beforeunload',()=>timer&&clearInterval(timer));
})();