document.addEventListener('DOMContentLoaded',()=>{
 const form=document.getElementById('bookingForm'); if(!form||!window.RBM)return;
 const cart=RBM.cart(), notice=document.getElementById('bookingServiceNotice'), summary=document.getElementById('agendaSummary'), dateEl=document.getElementById('bookingDate'), slots=document.getElementById('slotGrid'), timeEl=document.getElementById('selectedTime');
 if(!cart.length){notice.innerHTML='No service has been selected. <a href="../../rates.html"><strong>Choose services first</strong></a>.'; form.querySelector('button[type=submit]').disabled=true;} else notice.textContent='Your selected services are ready. Choose the service date and start time.';
 const t=RBM.totals(cart); summary.innerHTML=cart.map(i=>`<div class="cart-line"><span>${RBM.escapeHtml(i.name)}<br><small>${i.qty} × ${RBM.money(i.price)}</small></span><strong>${RBM.money(i.qty*i.price)}</strong></div>`).join('')+`<div class="cart-line"><span>Subtotal</span><strong>${RBM.money(t.subtotal)}</strong></div><div class="cart-line"><span>GST ${RBM.settings().gst}%</span><strong>${RBM.money(t.gst)}</strong></div><div class="cart-total">Estimated total ${RBM.money(t.total)}</div>`;
 const today=new Date(); today.setMinutes(today.getMinutes()-today.getTimezoneOffset()); dateEl.min=today.toISOString().slice(0,10);
 const baseSlots=['8:00 AM','9:00 AM','10:00 AM','11:00 AM','12:00 PM','1:00 PM','2:00 PM','3:00 PM','4:00 PM','5:00 PM','6:00 PM'];
 function renderSlots(){timeEl.value='';const date=dateEl.value;if(!date){slots.innerHTML='<p class="note">Select a date first.</p>';return}const rules=RBM.read(RBM.KEYS.availability,[]);const dayRule=rules.find(r=>r.date===date); const blocked=dayRule?.blocked||[]; const closed=dayRule?.closed; const booked=RBM.bookings().filter(b=>b.date===date&&b.status!=='Cancelled').map(b=>b.time); const unavailable=[...new Set([...blocked,...booked])]; slots.innerHTML=baseSlots.map(s=>`<button type="button" class="slot ${closed||unavailable.includes(s)?'blocked':''}" data-time="${s}" ${closed||unavailable.includes(s)?'disabled':''}>${s}</button>`).join(''); slots.querySelectorAll('.slot:not(.blocked)').forEach(b=>b.onclick=()=>{slots.querySelectorAll('.slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');timeEl.value=b.dataset.time;});}
 dateEl.addEventListener('change',renderSlots); renderSlots();
 form.addEventListener('submit',e=>{e.preventDefault();if(!timeEl.value){document.getElementById('bookingMsg').textContent='Please select an available start time.';return}const fd=Object.fromEntries(new FormData(form).entries());const booking={id:'RB-'+Date.now().toString().slice(-10),...fd,items:cart,subtotal:t.subtotal,gst:t.gst,total:t.total,status:'Pending Confirmation',paymentStatus:'Pending',createdAt:new Date().toISOString()};sessionStorage.setItem('rbm_pending_booking',JSON.stringify(booking));location.href='../../payment.html';});
});
