(function(){
const loginSection=document.getElementById('adminLoginSection'),dash=document.getElementById('adminDashboard'),loginForm=document.getElementById('adminLoginForm'),loginMsg=document.getElementById('loginMsg');let token=sessionStorage.getItem('rbm_admin_token')||'';let userEmail='';
const esc=RBM.escapeHtml;
function auth(){return token}
function msg(el,t){if(el)el.textContent=t||''}
async function verify(){if(!token)return false;try{const u=await RBMData.me(token);userEmail=u.email||'';const check=await RBMData.table.get('admin_users','select=user_id&limit=1',token);return Array.isArray(check)&&check.length>0}catch{return false}}
async function showDashboard(){loginSection.hidden=true;dash.hidden=false;document.getElementById('adminIdentity').textContent=userEmail||'RB Moving Admin';await Promise.all([loadBookings(),loadBlocks(),loadServices(),loadReviews(),loadSettings()])}
async function start(){if(!RBMData.configured()){loginMsg.textContent='Supabase must be configured in supabase-config.js before Administration can be used.';return}if(await verify())showDashboard();else{sessionStorage.removeItem('rbm_admin_token');token=''}}
loginForm.onsubmit=async e=>{e.preventDefault();msg(loginMsg,'Signing in…');try{const r=await RBMData.signIn(document.getElementById('adminEmail').value,document.getElementById('adminPassword').value);token=r.access_token;sessionStorage.setItem('rbm_admin_token',token);if(!(await verify()))throw new Error('This account is not authorized as an RB Moving administrator.');msg(loginMsg,'');showDashboard()}catch(err){msg(loginMsg,err.message||'Unable to sign in.');sessionStorage.removeItem('rbm_admin_token');token=''}};
document.getElementById('logoutBtn').onclick=()=>{sessionStorage.removeItem('rbm_admin_token');location.reload()};
document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('pane-'+b.dataset.tab).classList.add('active')});
async function loadBookings(){const body=document.getElementById('bookingsBody');body.innerHTML='<tr><td colspan="7">Loading…</td></tr>';try{const rows=await RBMData.table.get('bookings','select=id,reference,first_name,last_name,phone,email,service_date,start_slot,origin,destination,details,subtotal,gst_amount,total_estimate,status,job_status,invoice_status,payment_status,created_at&order=service_date.asc,start_slot.asc',auth());const items=await RBMData.table.get('booking_items','select=booking_id,service_name,qty,unit_price,unit,line_total',auth());const invoices=await RBMData.table.get('invoices','select=id,invoice_number,booking_id,final_amount,status,issued_at&order=issued_at.desc',auth());const byItems={};items.forEach(i=>(byItems[i.booking_id]??=[]).push(i));const byInv=Object.fromEntries(invoices.map(i=>[i.booking_id,i]));const active=rows.filter(x=>String(x.status).toLowerCase()!=='cancelled').length;document.getElementById('adminStats').innerHTML=`<div><strong>${rows.length}</strong><span>Total bookings</span></div><div><strong>${active}</strong><span>Active</span></div><div><strong>${invoices.length}</strong><span>Invoices</span></div>`;body.innerHTML=rows.length?rows.map(b=>{const inv=byInv[b.id],sv=(byItems[b.id]||[]).map(i=>`${esc(i.service_name)} × ${i.qty}`).join('<br>');return `<tr><td><strong>${esc(b.service_date)}</strong><br>${esc(b.start_slot)}<br><small>${esc(b.reference)}</small></td><td>${esc(b.first_name)} ${esc(b.last_name)}<br><a href="tel:${esc(b.phone)}">${esc(b.phone)}</a><br><a href="mailto:${esc(b.email)}">${esc(b.email)}</a><br><small>${esc(b.origin)} → ${esc(b.destination)}</small></td><td>${sv||'—'}</td><td>${RBM.money(b.total_estimate)}</td><td><select data-booking-status="${b.id}"><option ${b.status==='Confirmed'?'selected':''}>Confirmed</option><option ${b.status==='Cancelled'?'selected':''}>Cancelled</option></select><select data-job-status="${b.id}"><option ${b.job_status==='Scheduled'?'selected':''}>Scheduled</option><option ${b.job_status==='In Progress'?'selected':''}>In Progress</option><option ${b.job_status==='Completed'?'selected':''}>Completed</option></select></td><td>${inv?`<strong>${esc(inv.invoice_number)}</strong><br>${RBM.money(inv.final_amount)}<br><small>${esc(inv.status)}</small><br><button class="small-btn" data-copy-invoice="${esc(inv.invoice_number)}">Copy payment link</button>`:`<label class="inline-admin-field">Final CAD<input type="number" step="0.01" min="0.01" data-final="${b.id}" value="${Number(b.total_estimate).toFixed(2)}"></label><button class="small-btn" data-invoice="${b.id}">Create invoice</button>`}</td><td><button class="small-btn" data-save-booking="${b.id}">Save</button></td></tr>`}).join(''):'<tr><td colspan="7">No bookings yet.</td></tr>';
body.querySelectorAll('[data-save-booking]').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.saveBooking;const status=body.querySelector(`[data-booking-status="${id}"]`).value,job_status=body.querySelector(`[data-job-status="${id}"]`).value;await RBMData.table.patch('bookings',`id=eq.${id}`,{status,job_status,updated_at:new Date().toISOString()},auth());await loadBookings();await loadBlocks()});
body.querySelectorAll('[data-invoice]').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.invoice,amount=Number(body.querySelector(`[data-final="${id}"]`).value);if(!(amount>0))return;const num='INV-'+Date.now().toString().slice(-10);await RBMData.table.post('invoices',{invoice_number:num,booking_id:id,final_amount:amount,status:'Issued'},auth());await RBMData.table.patch('bookings',`id=eq.${id}`,{invoice_status:'Issued',payment_status:'Payment Pending',updated_at:new Date().toISOString()},auth());await loadBookings()});
body.querySelectorAll('[data-copy-invoice]').forEach(btn=>btn.onclick=async()=>{const url=new URL('../../payment.html',location.href);url.searchParams.set('invoice',btn.dataset.copyInvoice);await navigator.clipboard.writeText(url.href);btn.textContent='Copied!';setTimeout(()=>btn.textContent='Copy payment link',1300)});
}catch(err){console.error(err);body.innerHTML=`<tr><td colspan="7">${esc(err.message)}</td></tr>`}}
document.getElementById('refreshBookings').onclick=loadBookings;
async function loadBlocks(){const el=document.getElementById('blockedList');try{const rows=await RBMData.table.get('availability_blocks','select=id,block_date,start_slot,reason,active&active=eq.true&order=block_date.asc,start_slot.asc',auth());el.innerHTML=rows.length?rows.map(x=>`<div class="admin-item"><div><strong>${esc(x.block_date)} · ${esc(x.start_slot||'Entire day')}</strong><small>${esc(x.reason||'Unavailable')}</small></div><button class="small-btn" data-unblock="${x.id}">Remove</button></div>`).join(''):'<p class="note">No manual blocks.</p>';el.querySelectorAll('[data-unblock]').forEach(b=>b.onclick=async()=>{await RBMData.table.patch('availability_blocks',`id=eq.${b.dataset.unblock}`,{active:false},auth());loadBlocks()})}catch(err){el.textContent=err.message}}
document.getElementById('addBlock').onclick=async()=>{const d=document.getElementById('blockDate').value;if(!d)return;await RBMData.table.post('availability_blocks',{block_date:d,start_slot:document.getElementById('blockTime').value||null,reason:document.getElementById('blockReason').value||null,active:true},auth());loadBlocks()};
async function loadServices(){const el=document.getElementById('serviceAdmin');try{const rows=await RBMData.table.get('services','select=*&order=sort_order.asc',auth());el.innerHTML=rows.map(s=>`<div class="admin-item service-admin-item"><div class="admin-grow"><strong>${esc(s.name)}</strong><small>${esc(s.description)}</small><div class="admin-inline"><label>Price<input type="number" step="0.01" data-price="${s.id}" value="${s.price}"></label><label>Minimum<input type="number" step="0.5" data-min="${s.id}" value="${s.minimum}"></label><label><input type="checkbox" data-active="${s.id}" ${s.active?'checked':''}> Active</label></div></div><button class="small-btn" data-save-service="${s.id}">Save</button></div>`).join('');el.querySelectorAll('[data-save-service]').forEach(b=>b.onclick=async()=>{const id=b.dataset.saveService;await RBMData.table.patch('services',`id=eq.${encodeURIComponent(id)}`,{price:Number(el.querySelector(`[data-price="${id}"]`).value),minimum:Number(el.querySelector(`[data-min="${id}"]`).value),active:el.querySelector(`[data-active="${id}"]`).checked,updated_at:new Date().toISOString()},auth());b.textContent='Saved';setTimeout(()=>b.textContent='Save',1000)})}catch(err){el.textContent=err.message}}
async function loadReviews(){const el=document.getElementById('reviewAdmin');try{const rows=await RBMData.table.get('reviews','select=*&order=sort_order.asc,created_at.desc',auth());el.innerHTML=rows.length?rows.map(r=>`<div class="admin-item"><div class="admin-grow"><strong>${'★'.repeat(r.rating)} · ${esc(r.author)}</strong><small>${esc(r.review_text)}</small></div><label><input type="checkbox" data-review-visible="${r.id}" ${r.visible?'checked':''}> Visible</label><button class="small-btn" data-delete-review="${r.id}">Delete</button></div>`).join(''):'<p class="note">No reviews loaded yet.</p>';el.querySelectorAll('[data-review-visible]').forEach(c=>c.onchange=()=>RBMData.table.patch('reviews',`id=eq.${c.dataset.reviewVisible}`,{visible:c.checked,updated_at:new Date().toISOString()},auth()));el.querySelectorAll('[data-delete-review]').forEach(b=>b.onclick=async()=>{await RBMData.table.del('reviews',`id=eq.${b.dataset.deleteReview}`,auth());loadReviews()})}catch(err){el.textContent=err.message}}
document.getElementById('addReview').onclick=async()=>{const author=document.getElementById('reviewAuthor').value.trim(),review_text=document.getElementById('reviewText').value.trim();if(!author||!review_text)return;await RBMData.table.post('reviews',{author,rating:Number(document.getElementById('reviewRating').value),review_text,review_date:document.getElementById('reviewDate').value||null,source:'Google',source_url:document.getElementById('reviewUrl').value||null,visible:true},auth());document.getElementById('reviewAuthor').value='';document.getElementById('reviewText').value='';loadReviews()};
async function loadSettings(){try{const rows=await RBMData.table.get('settings','id=eq.1&select=*',auth()),s=rows[0];if(s){document.getElementById('gstRate').value=s.gst_rate;document.getElementById('businessHours').value=s.business_hours}}catch(e){console.error(e)}}
document.getElementById('saveSettings').onclick=async()=>{await RBMData.table.patch('settings','id=eq.1',{gst_rate:Number(document.getElementById('gstRate').value),business_hours:document.getElementById('businessHours').value,updated_at:new Date().toISOString()},auth());alert('Settings saved.')};
document.getElementById('exportBtn').onclick=async()=>{const rows=await RBMData.table.get('bookings','select=reference,service_date,start_slot,first_name,last_name,phone,email,origin,destination,total_estimate,status,job_status,invoice_status,payment_status&order=service_date.asc',auth());const heads=['Booking','Date','Time','First Name','Last Name','Phone','Email','Origin','Destination','Estimated Total','Booking Status','Job Status','Invoice Status','Payment Status'];const vals=rows.map(r=>[r.reference,r.service_date,r.start_slot,r.first_name,r.last_name,r.phone,r.email,r.origin,r.destination,r.total_estimate,r.status,r.job_status,r.invoice_status,r.payment_status]);const csv=[heads,...vals].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='rb-moving-bookings.csv';a.click()};
start();
})();
