(function(){
document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tab,.admin-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('pane-'+b.dataset.tab).classList.add('active')});
function renderBookings(){const a=RBM.bookings(),body=document.getElementById('bookingsBody');document.getElementById('adminStats').innerHTML=`<div><strong>${a.length}</strong><span>Total bookings</span></div><div><strong>${a.filter(x=>x.status==='Pending Confirmation').length}</strong><span>Pending confirmation</span></div><div><strong>${a.filter(x=>x.paymentStatus==='Demo Approved').length}</strong><span>Demo paid</span></div>`;body.innerHTML=a.length?a.map((b,idx)=>`<tr><td>${RBM.escapeHtml(b.date)}<br>${RBM.escapeHtml(b.time)}</td><td><strong>${RBM.escapeHtml(b.firstName)} ${RBM.escapeHtml(b.lastName)}</strong><br>${RBM.escapeHtml(b.phone)}<br><small>${RBM.escapeHtml(b.email)}</small></td><td>${(b.items||[]).map(i=>`${RBM.escapeHtml(i.name)} (${i.qty})`).join('<br>')}</td><td>${RBM.money(b.total)}</td><td><span class="pill">${RBM.escapeHtml(b.paymentStatus||'Unpaid')}</span></td><td><select data-status="${idx}">${['New','Awaiting Payment','Pending Confirmation','Confirmed','In Progress','Completed','Cancelled'].map(s=>`<option ${b.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join(''):'<tr><td colspan="6">No bookings saved in this browser yet.</td></tr>';body.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>{const x=RBM.bookings();x[Number(s.dataset.status)].status=s.value;RBM.saveBookings(x);renderBookings()});}
function renderBlocks(){const a=RBM.read(RBM.KEYS.availability,[]);document.getElementById('blockedList').innerHTML=a.length?a.map((x,i)=>`<div class="admin-row"><span><strong>${RBM.escapeHtml(x.date)}</strong> · ${x.time==='ALL'?'Entire day':RBM.escapeHtml(x.time)}</span><button class="small-btn" data-unblock="${i}">Remove</button></div>`).join(''):'<p class="note">No blocked dates or times.</p>';document.querySelectorAll('[data-unblock]').forEach(b=>b.onclick=()=>{const x=RBM.read(RBM.KEYS.availability,[]);x.splice(Number(b.dataset.unblock),1);RBM.write(RBM.KEYS.availability,x);renderBlocks()});}
function renderServices(){const a=RBM.services();document.getElementById('serviceAdmin').innerHTML=a.map((s,i)=>`<div class="admin-row service-edit"><div><strong>${RBM.escapeHtml(s.name)}</strong><br><small>${RBM.escapeHtml(s.category)}</small></div><label>Price<input type="number" step="0.01" value="${s.price}" data-price="${i}"></label><label>Min hours<input type="number" step="0.5" min="0.5" value="${s.minimum}" data-min="${i}"></label><label class="toggle-label"><input type="checkbox" data-active="${i}" ${s.active?'checked':''}> Active</label></div>`).join('');document.querySelectorAll('[data-price]').forEach(e=>e.onchange=()=>updateService(e,'price'));document.querySelectorAll('[data-min]').forEach(e=>e.onchange=()=>updateService(e,'minimum'));document.querySelectorAll('[data-active]').forEach(e=>e.onchange=()=>updateService(e,'active'));}
function updateService(el,key){const a=RBM.services(),i=Number(el.dataset[key==='price'?'price':key==='minimum'?'min':'active']);a[i][key]=key==='active'?el.checked:Number(el.value);RBM.write(RBM.KEYS.services,a);renderServices();}
function renderReviews(){const a=RBM.reviews();document.getElementById('reviewAdmin').innerHTML=a.length?a.map((r,i)=>`<div class="admin-row review-edit"><div><strong>${RBM.escapeHtml(r.author)}</strong> · ${'★'.repeat(Number(r.rating)||5)}<br><span>${RBM.escapeHtml(r.text)}</span></div><label class="toggle-label"><input type="checkbox" data-review-visible="${i}" ${r.visible?'checked':''}> Show</label><button class="small-btn" data-review-remove="${i}">Delete</button></div>`).join(''):'<p class="note">No reviews entered yet.</p>';document.querySelectorAll('[data-review-visible]').forEach(e=>e.onchange=()=>{const x=RBM.reviews();x[Number(e.dataset.reviewVisible)].visible=e.checked;RBM.write(RBM.KEYS.reviews,x);renderReviews()});document.querySelectorAll('[data-review-remove]').forEach(e=>e.onclick=()=>{const x=RBM.reviews();x.splice(Number(e.dataset.reviewRemove),1);RBM.write(RBM.KEYS.reviews,x);renderReviews()});}
document.getElementById('addBlock').onclick=()=>{const d=document.getElementById('blockDate').value,t=document.getElementById('blockTime').value;if(!d)return;const a=RBM.read(RBM.KEYS.availability,[]);if(!a.some(x=>x.date===d&&x.time===t))a.push({date:d,time:t,blocked:true});RBM.write(RBM.KEYS.availability,a);renderBlocks();};
document.getElementById('addReview').onclick=()=>{const author=document.getElementById('reviewAuthor').value.trim(),text=document.getElementById('reviewText').value.trim(),rating=Number(document.getElementById('reviewRating').value);if(!author||!text)return;const a=RBM.reviews();a.unshift({author,text,rating,visible:true,source:'Google'});RBM.write(RBM.KEYS.reviews,a);document.getElementById('reviewAuthor').value='';document.getElementById('reviewText').value='';renderReviews();};
document.getElementById('exportBtn').onclick=()=>{const a=RBM.bookings(),heads=['Booking','Date','Time','Name','Phone','Email','Origin','Destination','Services','Subtotal','GST','Total','Payment','Reference','Status'],rows=a.map(b=>[b.id,b.date,b.time,`${b.firstName||''} ${b.lastName||''}`,b.phone,b.email,b.origin,b.destination,(b.items||[]).map(i=>`${i.name} x ${i.qty}`).join('; '),b.subtotal,b.gst,b.total,b.paymentStatus,b.paymentReference,b.status]);const csv=[heads,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='rb-moving-bookings.csv';link.click();};
renderBookings();renderBlocks();renderServices();renderReviews();
})();
