(function(){
const form=document.getElementById('bookingForm'); if(!form) return;
const cart=RBM.cart(), summary=document.getElementById('scheduleSummary'), dateEl=document.getElementById('bookingDate'), slots=document.getElementById('timeSlots'), timeInput=document.getElementById('bookingTime'), msg=document.getElementById('bookingMsg');
if(!cart.length){summary.innerHTML='<div class="notice"><strong>Your cart is empty.</strong><br>Select at least one service before scheduling.</div><a class="btn primary full" href="../../rates.html">Choose Services</a>'; form.querySelector('button[type=submit]').disabled=true;} else {const t=RBM.totals(cart);summary.innerHTML=cart.map(i=>`<div class="cart-line"><div><strong>${RBM.escapeHtml(i.name)}</strong><br><small>${i.qty} × ${RBM.money(i.price)} / ${RBM.escapeHtml(i.unit)}</small></div><strong>${RBM.money(i.qty*i.price)}</strong></div>`).join('')+`<div class="cart-line"><span>Subtotal</span><strong>${RBM.money(t.subtotal)}</strong></div><div class="cart-line"><span>GST ${RBM.settings().gst}%</span><strong>${RBM.money(t.gst)}</strong></div><div class="cart-total"><span>Estimated total</span><strong>${RBM.money(t.total)}</strong></div>`;}
const today=new Date(); today.setMinutes(today.getMinutes()-today.getTimezoneOffset()); dateEl.min=today.toISOString().split('T')[0];
const base=['8:00 AM','9:00 AM','10:00 AM','11:00 AM','12:00 PM','1:00 PM','2:00 PM','3:00 PM','4:00 PM','5:00 PM','6:00 PM'];
function blocked(){return RBM.read(RBM.KEYS.availability,[])}
function renderSlots(){timeInput.value=''; const d=dateEl.value; if(!d){slots.innerHTML='<span class="note">Choose a date to see available times.</span>';return} const b=blocked(); const dayOff=b.some(x=>x.date===d&&x.time==='ALL'&&x.blocked); const bookings=RBM.bookings(); slots.innerHTML=base.map(t=>{const unavailable=dayOff||b.some(x=>x.date===d&&x.time===t&&x.blocked)||bookings.some(x=>x.date===d&&x.time===t&&x.status!=='Cancelled');return `<button type="button" class="time-slot${unavailable?' unavailable':''}" data-time="${t}" ${unavailable?'disabled':''}>${t}${unavailable?' · Unavailable':''}</button>`}).join(''); slots.querySelectorAll('.time-slot:not(.unavailable)').forEach(btn=>btn.onclick=()=>{slots.querySelectorAll('.time-slot').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');timeInput.value=btn.dataset.time;});}
dateEl.addEventListener('change',renderSlots); renderSlots();
form.addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return;if(!timeInput.value){msg.textContent='Please select an available start time.';return}const data=Object.fromEntries(new FormData(form).entries()), t=RBM.totals(cart);const booking={id:'RB-'+Date.now().toString().slice(-10),...data,items:cart,subtotal:t.subtotal,gst:t.gst,total:t.total,status:'Awaiting Payment',paymentStatus:'Unpaid',createdAt:new Date().toISOString()};sessionStorage.setItem('rbm_pending_booking',JSON.stringify(booking));location.href='../../payment.html';});
})();
