(function(){
const KEYS={services:'rbm_services_v2',cart:'rbm_cart_v2',bookings:'rbm_bookings_v2',availability:'rbm_availability_v2',reviews:'rbm_reviews_v2',settings:'rbm_settings_v2'};
const defaults=[
{id:'labour',name:'1 Person Labour / Assembly',category:'Labour',description:'Loading help, furniture assembly, packing, organizing and on-site moving support.',price:50,unit:'hour',minimum:2,image:'assets/rb-moving-sofa.jpg',active:true},
{id:'pickup',name:'1 Mover + Pickup / Small Delivery',category:'Delivery',description:'Pickup truck service for Marketplace, IKEA, small moves, deliveries and light dump runs. Fuel included within Calgary.',price:75,unit:'hour',minimum:2,image:'assets/rb-moving-truck-team.jpg',active:true},
{id:'truck2',name:'2 Movers + Moving Box Truck',category:'Moving',description:'Professional two-person crew with box truck. Includes blankets, straps, shrink wrap, tape and dolly.',price:135,unit:'hour',minimum:2,image:'assets/service-box-truck.webp',active:true},
{id:'helper',name:'Additional Helper',category:'Add-on',description:'Extra labour for heavy or oversized items such as pianos, treadmills, pool tables and saunas.',price:50,unit:'helper/hour',minimum:2,image:'assets/service-heavy-moving.webp',active:true},
{id:'junk',name:'Dump Run / Junk Removal',category:'Junk Removal',description:'Pickup, loading and disposal support. Landfill charges are added from the official receipt.',price:75,unit:'hour',minimum:2,image:'assets/service-junk-removal.webp',active:true},
{id:'packing',name:'Packing & Unpacking Support',category:'Packing',description:'Careful packing, unpacking and organization assistance before or after your move.',price:50,unit:'hour',minimum:2,image:'assets/service-packing.webp',active:true}
];
const reviewDefaults=[];
function read(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function services(){let s=read(KEYS.services,null);if(!s){s=defaults;write(KEYS.services,s)}else{let changed=false;s=s.map(item=>{const d=defaults.find(x=>x.id===item.id);if(!d)return item;if(/\.svg(?:$|\?)/i.test(item.image||'')||item.image==='assets/hero-movers-photo.svg'||item.image==='assets/moving-marketing-panel.svg'||(item.id==='junk'&&item.image==='assets/rb-moving-truck-team.jpg')||(item.id==='packing'&&item.image==='assets/rb-moving-sofa.jpg')){changed=true;return {...item,image:d.image}}return item});if(changed)write(KEYS.services,s)}return s}
function cart(){return read(KEYS.cart,[])} function saveCart(v){write(KEYS.cart,v)}
function bookings(){return read(KEYS.bookings,[])} function saveBookings(v){write(KEYS.bookings,v)}
function reviews(){let r=read(KEYS.reviews,null);if(!r){r=reviewDefaults;write(KEYS.reviews,r)}return r}
function settings(){return read(KEYS.settings,{gst:5,businessHours:'8:00 AM–8:00 PM',minHours:2})}
function money(n){return new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n||0))}
function totals(items){const subtotal=items.reduce((s,i)=>s+(Number(i.price)*Number(i.qty)),0),gst=subtotal*(Number(settings().gst||0)/100);return{subtotal,gst,total:subtotal+gst}}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addToCart(id,qty){const s=services().find(x=>x.id===id);if(!s)return;qty=Math.max(Number(qty)||s.minimum||1,s.minimum||1);let c=cart();const e=c.find(x=>x.id===id);if(e)e.qty=qty;else c.push({id:s.id,name:s.name,price:s.price,unit:s.unit,qty});saveCart(c);renderCart();}
function removeFromCart(id){saveCart(cart().filter(x=>x.id!==id));renderCart()}
function renderServices(){const el=document.getElementById('serviceGrid');if(!el)return;el.innerHTML=services().filter(s=>s.active).map(s=>`<article class="service-card"><img src="${escapeHtml(s.image)}" alt="${escapeHtml(s.name)}"><div class="service-card-body"><span class="badge">${escapeHtml(s.category)}</span><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description)}</p><div class="service-meta"><div><div class="service-price">${money(s.price)}</div><small>per ${escapeHtml(s.unit)} · ${s.minimum||1}-hour minimum</small></div></div><div class="qty-row"><label>Hours <input id="qty-${s.id}" type="number" min="${s.minimum||1}" step="0.5" value="${s.minimum||1}"></label><button class="btn primary small-btn" data-add="${s.id}">Add service</button></div></div></article>`).join('');el.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add,document.getElementById('qty-'+b.dataset.add).value));}
function renderCart(){const el=document.getElementById('cartContents');if(!el)return;const c=cart();if(!c.length){el.innerHTML='<p class="muted-light">No services selected yet.</p>';return}const t=totals(c);el.innerHTML=c.map(i=>`<div class="cart-line"><div><strong>${escapeHtml(i.name)}</strong><br><small>${i.qty} × ${money(i.price)} / ${escapeHtml(i.unit)}</small></div><div><strong>${money(i.qty*i.price)}</strong><br><button class="small-btn" data-remove="${i.id}">Remove</button></div></div>`).join('')+`<div class="cart-line"><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div><div class="cart-line"><span>GST ${settings().gst}%</span><strong>${money(t.gst)}</strong></div><div class="cart-total">Estimated total: ${money(t.total)}</div><a class="btn primary full" style="margin-top:16px" href="modules/agenda/agenda.html">Continue to schedule</a>`;el.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeFromCart(b.dataset.remove));}
function renderReviews(){const el=document.getElementById('reviewGrid');if(!el)return;const vis=reviews().filter(r=>r.visible);if(!vis.length){el.innerHTML='<div class="notice">Selected Google reviews will appear here after the owner adds or syncs them in Administration. This avoids publishing invented testimonials.</div>';return}el.innerHTML=vis.slice(0,6).map(r=>`<blockquote><div class="review-stars">${'★'.repeat(Math.max(1,Math.min(5,Number(r.rating)||5)))}</div>“${escapeHtml(r.text)}”<cite>${escapeHtml(r.author)} · Google review</cite></blockquote>`).join('')}
window.RBM={KEYS,read,write,services,cart,saveCart,bookings,saveBookings,reviews,settings,money,totals,escapeHtml,renderServices,renderCart,renderReviews};
document.addEventListener('DOMContentLoaded',()=>{renderServices();renderCart();renderReviews();});
})();
