-- Sumaq Reservations Staff Portal migration
-- Run once in Supabase > SQL Editor before using staff-reservations.html.
-- Safe to run more than once.

alter table public.reservations add column if not exists table_label text not null default '';
alter table public.reservations add column if not exists staff_note text not null default '';

create table if not exists public.reservation_activity (
  id bigint generated by default as identity primary key,
  reservation_id uuid not null references public.reservations(id) on delete cascade,
  reservation_date date not null,
  action text not null,
  details text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists reservation_activity_date_idx on public.reservation_activity(reservation_date,created_at desc);
create index if not exists reservation_activity_reservation_idx on public.reservation_activity(reservation_id,created_at desc);
alter table public.reservation_activity enable row level security;

-- Existing authenticated administration users may review the activity trail.
drop policy if exists "Admin reads reservation activity" on public.reservation_activity;
create policy "Admin reads reservation activity" on public.reservation_activity for select to authenticated using (true);

create or replace function public.sumaq_log_reservation_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.reservation_activity(reservation_id,reservation_date,action,details)
    values(new.id,new.reservation_date,'New reservation',trim(coalesce(new.first_name,'') || ' ' || coalesce(new.last_name,'')) || ' · ' || new.party_size || ' guests · ' || to_char(new.reservation_time,'HH12:MI AM'));
    return new;
  end if;

  if old.status is distinct from new.status then
    insert into public.reservation_activity(reservation_id,reservation_date,action,details)
    values(new.id,new.reservation_date,'Status updated',trim(coalesce(new.first_name,'') || ' ' || coalesce(new.last_name,'')) || ' · ' || coalesce(old.status,'') || ' → ' || coalesce(new.status,''));
  end if;

  if old.table_label is distinct from new.table_label then
    insert into public.reservation_activity(reservation_id,reservation_date,action,details)
    values(new.id,new.reservation_date,'Table updated',trim(coalesce(new.first_name,'') || ' ' || coalesce(new.last_name,'')) || ' · ' || coalesce(nullif(new.table_label,''),'Unassigned'));
  end if;

  if old.staff_note is distinct from new.staff_note and coalesce(new.staff_note,'') <> '' then
    insert into public.reservation_activity(reservation_id,reservation_date,action,details)
    values(new.id,new.reservation_date,'Staff note updated',trim(coalesce(new.first_name,'') || ' ' || coalesce(new.last_name,'')) || ' · ' || left(new.staff_note,180));
  end if;

  return new;
end;
$$;

drop trigger if exists sumaq_reservation_activity_trigger on public.reservations;
create trigger sumaq_reservation_activity_trigger
after insert or update of status,table_label,staff_note on public.reservations
for each row execute function public.sumaq_log_reservation_activity();
